sudo: required
language: generic

services:
  - docker

cache:
  directories:
    - build/vendor

before_install:
  - docker pull boxdot/alpine-clang

script:
  - docker run -t -v $(pwd):/root/renderer -w /root/renderer boxdot/alpine-clang scripts/build-and-test.sh

after_success:
  - docker run -t -v $(pwd):/root/renderer -w /root/renderer -e "TRAVIS_JOB_ID=$TRAVIS_JOB_ID" boxdot/alpine-clang scripts/collect-coverage.sh
  - docker run -t -v $(pwd):/root/renderer -e "B2_APP_KEY=${B2_APP_KEY}" -e "B2_ACCOUNT_ID=${B2_ACCOUNT_ID}" -w /root/renderer boxdot/alpine-clang scripts/render-samples.sh scenes/cornell_box.blend output $TRAVIS_COMMIT
