sudo: required

services:
  - docker

cache:
  directories:
    - build/vendor

before_install:
  - docker pull boxdot/alpine-clang

script:
  - docker run -v $(pwd):/root/renderer -w /root/renderer boxdot/alpine-clang ./scripts/build-and-test.sh
