language: cpp

cache:
  directories:
    - build/vendor

compiler: clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
      - george-edison55-precise-backports
    packages:
      - clang-3.6
      - cmake
      - cmake-data
env:
  - COMPILER=clang++-3.6

before_install:
  - pip install --user cpp-coveralls

script:
  - mkdir -p build && cd build
  - cmake .. -DCMAKE_CXX_COMPILER=$COMPILER -DCOVERAGE=1
  - make
  - make test

after_success:
  - coveralls -r .. -b . --exclude build/vendor --exclude tests --gcov-options '\-lp'
